# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    # Membuka halaman diagnosis
    def bukaHalamanDiagnosis(self):
        from InputGejala import Ui_Diagnosis
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Diagnosis()
        self.ui.setupUi(self.window)
        self.window.show()

    # Membuka halaman artikel3
    def bukaHalamanArtikel3(self):
        from artikel import Ui_Artikel3
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Artikel3()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 715)
        MainWindow.setStyleSheet("background-color: rgb(250, 249, 249);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.diagnosisButton = QtWidgets.QPushButton(self.centralwidget)
        self.diagnosisButton.setGeometry(QtCore.QRect(300, 330, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.diagnosisButton.setFont(font)
        self.diagnosisButton.setStyleSheet("background-color:#2B65EC;\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:20px;\n"
"border-color:grey")
        self.diagnosisButton.setObjectName("diagnosisButton")
        self.diagnosisButton.clicked.connect(self.bukaHalamanDiagnosis)

        self.article1_Button = QtWidgets.QPushButton(self.centralwidget)
        self.article1_Button.setGeometry(QtCore.QRect(120, 510, 241, 134))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.article1_Button.setFont(font)
        self.article1_Button.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: black;\n"
"border-style: outset;\n"
"border-width : 2px;")
        self.article1_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Gambar/fil-mazzarino-VyOtjKmSnKQ-unsplash.jpg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.article1_Button.setIcon(icon)
        self.article1_Button.setIconSize(QtCore.QSize(250, 140))
        self.article1_Button.setObjectName("article1_Button")
        self.article2_Button = QtWidgets.QPushButton(self.centralwidget)
        self.article2_Button.setGeometry(QtCore.QRect(380, 510, 241, 134))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.article2_Button.setFont(font)
        self.article2_Button.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: black;\n"
"border-style: outset;\n"
"border-width : 2px;")
        self.article2_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Gambar/lala-azizli-AeQ9649tme4-unsplash.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.article2_Button.setIcon(icon1)
        self.article2_Button.setIconSize(QtCore.QSize(300, 165))
        self.article2_Button.setObjectName("article2_Button")
        self.article3_Button = QtWidgets.QPushButton(self.centralwidget)
        self.article3_Button.setGeometry(QtCore.QRect(630, 510, 241, 134))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.article3_Button.setFont(font)
        self.article3_Button.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: black;\n"
"border-style: outset;\n"
"border-width : 2px;")
        self.article3_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Gambar/amy-syiek-4irgyik6Q3U-unsplash.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.article3_Button.setIcon(icon2)
        self.article3_Button.setIconSize(QtCore.QSize(250, 250))
        self.article3_Button.setObjectName("article3_Button")
        self.article3_Button.clicked.connect(self.bukaHalamanArtikel3)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 470, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(250, 249, 249);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 100, 51, 61))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setBaseSize(QtCore.QSize(0, 0))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Icon/Web 1920 – 2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 100, 71, 71))
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Icon/Web 1920 – 1.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(760, 100, 71, 71))
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setBaseSize(QtCore.QSize(0, 0))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Icon/Web 1920 – 4.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 100, 71, 71))
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setBaseSize(QtCore.QSize(0, 0))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Icon/Web 1920 – 3.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 40, 761, 201))
        self.label_7.setStyleSheet("border-width: 2px;\n"
"border-style: outset;\n"
"border-radius:10px;\n"
"\n"
"border-color: rgb(0, 0, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 180, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(320, 170, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(530, 170, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(730, 180, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_7.raise_()
        self.article1_Button.raise_()
        self.diagnosisButton.raise_()
        self.article2_Button.raise_()
        self.article3_Button.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.diagnosisButton.setText(_translate("MainWindow", "Diagnosis Sekarang"))
        self.label.setText(_translate("MainWindow", "Artikel Kesehatan Terbaru"))
        self.label_2.setText(_translate("MainWindow", "Cara Penggunaan"))
        self.label_8.setText(_translate("MainWindow", "Klik Diagnisis Sekarang"))
        self.label_9.setText(_translate("MainWindow", "Masukan Gejala Yang Dialami"))
        self.label_10.setText(_translate("MainWindow", "Pilih Hasil Diagnosis Teratas"))
        self.label_11.setText(_translate("MainWindow", "Lihat Detail Penyakit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
