# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Diagnosis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_Diagnosis(object):
    def __init__(self):
        # inisialisasi database yang dipakai
        con = pymysql.connect(db='db_diagnosispenyakit', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        self.cur = con.cursor()

    # Membuka halaman hasil diagnosis
    def bukaHalamanHasilDiagnosis(self):
        if self.listWidget.count() > 0:
            from HasilDiagnosis import Ui_HasilDiagnosis
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_HasilDiagnosis()
            self.ui.setupUi(self.window)
            self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1313, 715)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 130, 641, 381))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label_judul = QtWidgets.QLabel(self.groupBox)
        self.label_judul.setGeometry(QtCore.QRect(100, 80, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setObjectName("label_judul")
        self.Gejala_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.Gejala_comboBox.setGeometry(QtCore.QRect(150, 170, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.Gejala_comboBox.setFont(font)
        self.Gejala_comboBox.setObjectName("Gejala_comboBox")

        self.label_gejala = QtWidgets.QLabel(self.groupBox)
        self.label_gejala.setGeometry(QtCore.QRect(70, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_gejala.setFont(font)
        self.label_gejala.setObjectName("label_gejala")
        self.addGejala_Button = QtWidgets.QPushButton(self.groupBox)
        self.addGejala_Button.setGeometry(QtCore.QRect(360, 260, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addGejala_Button.setFont(font)
        self.addGejala_Button.setStyleSheet("background-color:#2B65EC;\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:20px;\n"
"border-color:grey")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.addGejala_Button.setIcon(icon)
        self.addGejala_Button.setIconSize(QtCore.QSize(30, 30))
        self.addGejala_Button.setObjectName("addGejala_Button")
        self.addGejala_Button.clicked.connect(self.tambahGejalaYangDialami_PadaListWidget)

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(690, 50, 591, 601))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(130, 30, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setGeometry(QtCore.QRect(40, 90, 521, 351))
        self.listWidget.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width: 2px;\n"
"border-style:outset;")
        self.listWidget.setLineWidth(1)
        self.listWidget.setObjectName("listWidget")
        self.Diagnosis_P_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Diagnosis_P_Button.setGeometry(QtCore.QRect(200, 540, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Diagnosis_P_Button.setFont(font)
        self.Diagnosis_P_Button.setStyleSheet("background-color:#2B65EC;\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:20px;\n"
"border-color:grey")
        self.Diagnosis_P_Button.setObjectName("Diagnosis_P_Button")
        self.Diagnosis_P_Button.clicked.connect(self.masukanInputanGejalaYangDialami_PadaListWidget_KedalamDatabase)
        self.Diagnosis_P_Button.clicked.connect(self.bukaHalamanHasilDiagnosis)

        self.hapusGejala_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.hapusGejala_Button.setGeometry(QtCore.QRect(60, 450, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.hapusGejala_Button.setFont(font)
        self.hapusGejala_Button.setStyleSheet("background-color:#2B65EC;\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:5px;\n"
"border-color: black;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/Trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.hapusGejala_Button.setIcon(icon1)
        self.hapusGejala_Button.setObjectName("hapusGejala_Button")
        self.hapusGejala_Button.clicked.connect(self.hapusGejalaYangDialami_PadaListWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1313, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Gejala"))
        self.label_judul.setText(_translate("MainWindow", "Masukkan Gejala yang Anda Alami"))

        self.Gejala_comboBox.clear() # Hapus Isi ComboBox

        ########################################################################################################
        # Memasukan Semua Daftar Gejala Penyakit Yang Ada Pada Database
        ########################################################################################################
        sql = "select distinct gejala from detailPenyakit"
        self.cur.execute(sql)

        daftarGejalaPenyakit = [] # Array untuk menampung daftar penyakit yang ada pada database

        for e in self.cur.fetchall(): # Memasukan hasil pencarian gejala penyakit pada database kedalam array
            daftarGejalaPenyakit += e

        for y in daftarGejalaPenyakit:
            if len(str(y)) != 0: # Memasukan gejala penyakit yang hanya ada isinya
                self.Gejala_comboBox.addItem(str(y))  # Menambah gejala penyakit pada ComboBox

        self.label_gejala.setText(_translate("MainWindow", "Gejala"))
        self.addGejala_Button.setText(_translate("MainWindow", "Tambah Gejala"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Daftar Cari Gejala"))
        self.label.setText(_translate("MainWindow", "Daftar Gejala yang Dialami"))
        self.Diagnosis_P_Button.setText(_translate("MainWindow", "Diagnosis Penyakit Sekarang"))
        self.hapusGejala_Button.setText(_translate("MainWindow", "Hapus Gejala"))

    # Tambah gejala penyakit yang dialami kedalam list widget
    def tambahGejalaYangDialami_PadaListWidget(self):
        self.listWidget.addItem(self.Gejala_comboBox.currentText())

    # Hapus gejala penyakit yang dialami pada list widget
    def hapusGejalaYangDialami_PadaListWidget(self):
        row = self.listWidget.currentRow()
        if row >= 0:
            self.listWidget.takeItem(row)

    # Memasukan gejala penyakit yang dialami kedalam database
    def masukanInputanGejalaYangDialami_PadaListWidget_KedalamDatabase(self):
        for x in range(self.listWidget.count()):
            sql = "insert into historiUser (histori_cariGejala) values ('%s')" % str(self.listWidget.item(x).text())
            self.cur.execute(sql)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Diagnosis()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
