# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datamhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from PyQt5.QtWidgets import *
from datamhs import *

class datamhs(QWidget):
    def __init__(self):
        super().__init__()
        self.datamhs = Ui_datamhs1()
        self.datamhs.setupUi(self)
        self.datamhs.Btn_Tambah.clicked.connect(self.submit)
        self.datamhs.Btn_edit.clicked.connect(self.edit)
        self.datamhs.Btn_hapus.clicked.connect(self.hapus)

    def submit(self):
        nim = self.datamhs.lineEdit_nim.text()
        nama = self.datamhs.lineEdit_nama.text()
        jurusan = self.datamhs.lineEdit_jurusan.text()
        no = self.datamhs.lineEdit_no.text()
        insert = (nim, nama, jurusan, no)
        print(insert)

        if self.datamhs.lineEdit_nim.text() and self.datamhs.lineEdit_nama.text() and self.datamhs.lineEdit_jurusan.text() and self.datamhs.lineEdit_no.text():
            con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO mhs(nim, nama, jurusan,no)" + "VALUES"+ str(insert)
            data = cur.execute(sql)
            Ui_MainWindow.messagebox(Ui_MainWindow,"SUKSES", "Data Berhasil di Submit")
        else:
            Ui_MainWindow.messagebox(Ui_MainWindow, "GAGAL","Mohon lengkapi form ")

    def edit(self):
        nim = self.datamhs.lineEdit_nim.text()
        nama = self.datamhs.lineEdit_nama.text()
        jurusan = self.datamhs.lineEdit_jurusan.text()
        no = self.datamhs.lineEdit_no.text()
        insert = (nim, nama, jurusan, no)

        if self.datamhs.lineEdit_nim.text() and self.datamhs.lineEdit_nama.text() and self.datamhs.lineEdit_jurusan.text() and self.datamhs.lineEdit_no.text():
            con = pymysql.connect(db='tubes_gui',
                                  user='root', passwd='', host='localhost', port=3306,
                                  autocommit=True)
            cur = con.cursor()
            sql = "UPDATE mhs set nama='" + str(nama) + "', jurusan='" + str(jurusan) + "', no='" + str(no) + "' where nim='" + str(nim) + "'"
            data = cur.execute(sql)
            Ui_MainWindow.messagebox(Ui_MainWindow, "SUKSES", "Data Berhasil di Submit")
        else:
            Ui_MainWindow.messagebox(Ui_MainWindow, "GAGAL", "Mohon lengkapi form ")

    def hapus(self):
        nim = self.datamhs.txtNim_2.text()

        if self.datamhs.txtNim_2.text():
            con = pymysql.connect(db='tubes_gui',
                                  user='root', passwd='', host='localhost', port=3306,
                                  autocommit=True)
            cur = con.cursor()
            sql = "DELETE from mhs where nim='" + str(nim) + "'"
            data = cur.execute(sql)
            Ui_MainWindow.messagebox(Ui_MainWindow, "SUKSES", "Data Berhasil di Hapus")
        else:
            Ui_MainWindow.messagebox(Ui_MainWindow, "GAGAL", "Mohon isi nim dengan sesuai ")


class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_datamhs1()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        self.koneksi()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 270, 191, 191))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_Form_Mhs = QtWidgets.QLabel(self.tab)
        self.label_Form_Mhs.setGeometry(QtCore.QRect(190, 40, 225, 29))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Form_Mhs.setFont(font)
        self.label_Form_Mhs.setObjectName("label_Form_Mhs")

        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(40, 80, 521, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_NIM = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_NIM.setObjectName("lineEdit_NIM")

        self.gridLayout.addWidget(self.lineEdit_NIM, 0, 1, 1, 1)
        self.Nama = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Nama.setFont(font)
        self.Nama.setObjectName("Nama")
        self.gridLayout.addWidget(self.Nama, 1, 0, 1, 1)
        self.lineEdit_Nama = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Nama.setObjectName("lineEdit_Nama")

        self.gridLayout.addWidget(self.lineEdit_Nama, 1, 1, 1, 1)
        self.Jurusan = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Jurusan.setFont(font)
        self.Jurusan.setObjectName("Jurusan")
        self.gridLayout.addWidget(self.Jurusan, 2, 0, 1, 1)
        self.lineEdit_Jurusan = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Jurusan.setObjectName("lineEdit_Jurusan")

        self.gridLayout.addWidget(self.lineEdit_Jurusan, 2, 1, 1, 1)
        self.No_Telp = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.No_Telp.setFont(font)
        self.No_Telp.setObjectName("No_Telp")
        self.gridLayout.addWidget(self.No_Telp, 3, 0, 1, 1)
        self.lineEdit_No_Telp = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_No_Telp.setObjectName("lineEdit_No_Telp")

        self.gridLayout.addWidget(self.lineEdit_No_Telp, 3, 1, 1, 1)
        self.NIM = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.NIM.setFont(font)
        self.NIM.setObjectName("NIM")
        self.gridLayout.addWidget(self.NIM, 0, 0, 1, 1)
        self.Btn_Submit = QtWidgets.QPushButton(self.tab)
        self.Btn_Submit.setGeometry(QtCore.QRect(480, 240, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Submit.setFont(font)
        self.Btn_Submit.setObjectName("Btn_Submit")
        self.Btn_Submit.clicked.connect(self.submit)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 601, 481))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("360_F_119115529_mEnw3lGpLdlDkfLgRcVSbFRuVl6sMDty.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_login_admin = QtWidgets.QLabel(self.tab_2)
        self.label_login_admin.setGeometry(QtCore.QRect(200, 130, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_login_admin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_login_admin.setFont(font)
        self.label_login_admin.setAutoFillBackground(False)
        self.label_login_admin.setWordWrap(False)
        self.label_login_admin.setObjectName("label_login_admin")

        self.Btn_Login = QtWidgets.QPushButton(self.tab_2)
        self.Btn_Login.setGeometry(QtCore.QRect(470, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Login.setFont(font)
        self.Btn_Login.setObjectName("Btn_Login")
        self.Btn_Login.clicked.connect(self.login)
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(60, 190, 481, 81))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_username = QtWidgets.QLabel(self.widget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_username.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_username.setFont(font)
        self.label_username.setAutoFillBackground(False)
        self.label_username.setWordWrap(False)
        self.label_username.setObjectName("label_username")
        self.gridLayout_2.addWidget(self.label_username, 0, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout_2.addWidget(self.lineEdit_username, 0, 1, 1, 1)

        self.lineEdit_pass = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.gridLayout_2.addWidget(self.lineEdit_pass, 1, 1, 1, 1)
        self.label_pass = QtWidgets.QLabel(self.widget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_pass.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_pass.setFont(font)
        self.label_pass.setAutoFillBackground(False)
        self.label_pass.setWordWrap(False)
        self.label_pass.setObjectName("label_pass")
        self.gridLayout_2.addWidget(self.label_pass, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Form_Mhs.setText(_translate("MainWindow", "Form Mahasiswa"))
        self.Nama.setText(_translate("MainWindow", "Nama"))
        self.Jurusan.setText(_translate("MainWindow", "Jurusan"))
        self.No_Telp.setText(_translate("MainWindow", "No.Telp"))
        self.NIM.setText(_translate("MainWindow", "NIM"))
        self.Btn_Submit.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Form"))
        self.label_login_admin.setText(_translate("MainWindow", "Login Admin"))
        self.Btn_Login.setText(_translate("MainWindow", "Login"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.label_pass.setText(_translate("MainWindow", "Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Admin"))


    def koneksi(self):
        con = pymysql.connect(db='db_mhs',
                              user='root', passwd='', host='localhost',
                              port=3306, autocommit=True)
        cur = con.cursor()
        if (cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def submit(self):
        nim = self.lineEdit_NIM.text()
        nama = self.lineEdit_Nama.text()
        jurusan = self.lineEdit_Jurusan.text()
        no = self.lineEdit_No_Telp.text()
        insert = (nim, nama, jurusan, no)
        print(insert)

        if self.lineEdit_NIM.text() and self.lineEdit_Nama.text() and self.lineEdit_Jurusan.text() and self.lineEdit_No_Telp.text():
            con = pymysql.connect(db='db_mhs',
                                  user='root', passwd='', host='localhost',
                                  port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO mhs(nim, nama, jurusan, no)" + "VALUES"+ str(insert)
            data = cur.execute(sql)
            self.messagebox("SUKSES", "Data Berhasil di Submit")
        else:
            self.messagebox("GAGAL", "Mohon lengkapi form ")

    def login(self):
        uname = self.lineEdit_username.text()
        pw = self.lineEdit_pass.text()
        con = pymysql.connect(db='db_mhs',
                              user='root', passwd='', host='localhost',
                              port=3306, autocommit=True)
        cur = con.cursor()
        sql = "SELECT * from admin where uname=%s and pw=%s"
        data = cur.execute(sql, (uname, pw))

        if(len(cur.fetchall())>0):
            self.openWindow()
        else:
            self.messagebox("GAGAL", "Username atau Password Salah ! ")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
